<?php
/**
 * @file
 * Code for the WalkHub feature.
 */

include_once 'walkhub.features.inc';

// Field name.
define('WALKTHROUGH_FIELD_STEPS', 'field_fc_steps');

/**
 * Implements hook_init().
 */
function walkhub_init() {
  $module_path = drupal_get_path('module', 'walkhub') ;
  drupal_add_js('misc/ajax.js', array('every_page' => TRUE));
  drupal_add_js($module_path . '/walkhub-ie-fixes.js', array('weight' => -11, 'group' => JS_DEFAULT, 'every_page' => TRUE));
  drupal_add_js($module_path . '/walkhub.js', array('weight' => -10, 'group' => JS_DEFAULT, 'every_page' => TRUE));
  drupal_add_library('system', 'ui.dialog', TRUE);
}

/**
 * Implements hook_block_info().
 */
function walkhub_block_info() {
  $blocks['floating_record_button'] = array(
    'info' => t('Floating Record a Walkthrough button'),
    'status' => TRUE,
    'region' => 'header',
    'weight' => 0,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    'pages' => 'walkthrough/record'
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function walkhub_block_view($delta = '') {
  $block = array();
  if (user_is_anonymous()) {
    return FALSE;
  }
  switch ($delta) {
    case 'floating_record_button':
      $form = drupal_get_form('walkhub_record_form', TRUE);
      $form = drupal_render($form);
      $block['content'] = theme('walkthrough__record__block', array('form' => $form));
      break;
  }
  return $block;
}

/**
 * Implements hook_menu().
 */
function walkhub_menu() {
  $items = array();

  $items['walkthrough/import'] = array(
    'title' => 'Import walkthrough',
    'description' => 'Multi step form to create walkthroughs.',
    'type' => MENU_CALLBACK,
    'access arguments' => array('create', 'walkthrough'),
    'access callback' => 'node_access',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('walkhub_create_walkthrough_form'),
    'file' => 'walkhub.pages.inc',
  );

  $items['walkthrough/record'] = array(
    'title' => 'Record walkthrough',
    'description' => 'Walkthrough recorder to create walkthroughs',
    'type' => MENU_CALLBACK,
    'access arguments' => array('create', 'walkthrough'),
    'access callback' => 'node_access',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('walkhub_record_form', FALSE),
    'file' => 'walkhub.pages.inc',
  );

  $items['node/%walkhub_walkthrough_node/start'] = array(
    'title' => 'Start walkthrough',
    'page callback' => 'walkhub_start_walkthrough',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'walkhub.pages.inc',
  );

  $items['node/%walkhub_walkthrough_node/embed.js'] = array(
    'title' => 'Embed walkthrough',
    'delivery callback' => 'walkthrough_deliver_embedjs',
    'page callback' => 'walkhub_embedjs_page',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
    'type' => MENU_CALLBACK,
    'file' => 'walkhub.pages.inc',
  );

  $items['node/%walkhub_walkthrough_node/selenium_export'] = array(
    'title' => 'Export to selenium',
    'page callback' => 'walkhub_selenium_export',
    'page arguments' => array(1),
    'access arguments' => array(1),
    'access callback' => 'walkhub_export_access',
    'type' => MENU_LOCAL_TASK,
    'file' => 'walkhub.export.inc',
  );

  $items['node/%walkhub_walkthrough_node/phpunit_export'] = array(
    'title' => 'Export to phpunit',
    'page callback' => 'walkhub_phpunit_export',
    'page arguments' => array(1),
    'access arguments' => array(1),
    'access callback' => 'walkhub_export_access',
    'type' => MENU_LOCAL_TASK,
    'file' => 'walkhub.export.inc',
  );

  $items['walkhub'] = array(
    'title' => 'Walkthrough is starting...',
    'page callback' => 'walkhub_walkhub_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'walkhub.pages.inc',
  );

  $items['admin/structure/walkhub-patterns'] = array(
    'title' => 'Walkhub patterns',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('walkhub_command_patterns_form'),
    'access arguments' => array('administer walkhub patterns'),
    'file' => 'walkhub.admin.inc',
  );

  $items['admin/config/services/walkhub'] = array(
    'title' => 'Walkhub configuration',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer walkthrough'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('walkhub_configuration_form'),
    'file' => 'walkhub.admin.inc'
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function walkhub_permission() {
  return array(
    'administer walkhub patterns' =>  array(
      'title' => t('Administer Walkhub patterns'),
    ),
    'administer walkthrough' => array(
      'title' => t('Administer walkthrough'),
    ),
    'export any walkthrough' => array(
      'title' => t('Export walkthrough'),
    ),
    'export own walkthrough' => array(
      'title' => t('Export own walkthrough'),
    ),
  );

}

/**
 * Loads a node if it's content type is 'walkthrough'.
 *
 * @param int $nid
 *   Node ID.
 *
 * @return bool|stdClass
 *   Node on success, false otherwise.
 */
function walkhub_walkthrough_node_load($nid) {
  $node = node_load($nid);

  if ($node && $node->type === 'walkthrough') {
    return $node;
  }

  return FALSE;
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Attach data attributes to the walkthrough play button.
 */
function walkhub_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  module_load_include('inc', 'walkhub');
  if ($data['actions']['count']) {
    foreach ($data['actions']['output'] as &$action) {
      if ($action['#link']['path'] === 'node/%/start') {
        $action['#link']['localized_options']['attributes']['class'][] = 'walkthrough-start';

        $loadfunc = reset($action['#link']['load_functions']);
        $path = explode('/', $action['#link']['href']);
        $nid = $path[1];
        if (is_callable($loadfunc)) {
          $walkthrough = $loadfunc($nid);
          if ($walkthrough) {
            $action['#link']['localized_options']['attributes'] += _walkhub_get_data_attributes($walkthrough);
          }
        }
        break;
      }
    }
  }
}

/**
 * Get data attributes to the walkthrough play button.
 *
 * @param stdClass $walkthrough
 *   Walkthrough to play.
 *
 * @return array
 *   Array of data attributes.
 */
function _walkhub_get_data_attributes(stdClass $walkthrough) {
  $attributes = array();

  // Have to load entities here by hand, instead of entity_uuid_load(), because we are working with local references.
  $prerequuids = walkhub_field_get_references('node', $walkthrough, 'field_prerequisites');
  $ids = entity_get_id_by_uuid('node', $prerequuids);
  $prereqs = entity_load('node', $ids);

  // Attach play via proxy flag.
  $proxy_url = variable_get('walkhub_proxy_url');
  if ($proxy_url && $walkthrough->field_play_via_proxy[LANGUAGE_NONE][0]['value']) {
    $attributes['data-walkthrough-proxy-url'] = $proxy_url;
  }

  // Attach walkthrough uuid.
  $attributes['data-walkthrough-uuid'] = $walkthrough->uuid;

  // Attach prerequisite parameters first (so it can be overridden by the walkthrough).
  foreach ($prereqs as $prereq) {
    foreach (_walkhub_get_parameters($prereq) as $parameter => $default_value) {
      $attributes["data-walkthrough-parameter-{$parameter}"] = $default_value;
    }
  }

  // Attach parameters.
  foreach (_walkhub_get_parameters($walkthrough) as $parameter => $default_value) {
    $attributes["data-walkthrough-parameter-{$parameter}"] = $default_value;
  }

  $attributes['data-embedjs'] = url("node/{$walkthrough->nid}/embed.js", array(
    'absolute' => TRUE,
  ));

  $i = 0;
  foreach ($prereqs as $prereq) {
    $attributes["data-walkthrough-prerequsite-{$i}-{$prereq->uuid}"] = check_plain($prereq->title);
  }

  $attributes['data-embedjskey'] = walkhub_get_id_hash($walkthrough);
  $attributes['data-social-sharing'] = variable_get('walkhub_social_sharing', TRUE);

  $attributes['data-walkthrough-edit-link'] = url("node/{$walkthrough->nid}/edit", array('absolute' => TRUE));

  $severity = field_get_items('node', $walkthrough, 'field_severity_of_the_change');

  if ($severity) {
    $severity_field = field_info_field('field_severity_of_the_change');
    $severity_info_instance = field_info_instance('node', 'field_severity_of_the_change', 'walkthrough');
    $attributes['data-walkthrough-severity'] =  $severity[0]['value'];
    $attributes['data-walkthrough-severity-text'] = t('@label: %severity', array('@label' => t($severity_info_instance['label']), '%severity' => t($severity_field['settings']['allowed_values'][$severity[0]['value']])));
  }

  return $attributes;
}

/**
 * Implements hook_menu_alter().
 */
function walkhub_menu_alter(&$items) {
  // Change clone module's link to local task.
  $items['node/%node/clone/%clone_token']['type'] = MENU_LOCAL_TASK;
}

/**
 * Implements hook_field_attach_validate().
 */
function walkhub_field_attach_validate($entity_type, $entity, &$errors) {
  static $parameter_blacklist = array(
    'q', 'destination', 'autostart', 'method',
  );
  if ($entity_type == 'field_collection_item' && !empty($entity->field_parameter_name)) {
    $lang = $entity->langcode();
    if (!$lang) {
      $lang = LANGUAGE_NONE;
    }
    $field_value = $entity->field_parameter_name[$lang][0]['value'];
    if (in_array($field_value, $parameter_blacklist)) {
      $errors['field_parameter_name'][$lang][0][] = array(
        'error' => 'field_parameter_name_blacklisted',
        'message' => t('This name is restricted. It cannot be used for parameters.'),
      );
    }
    if ($field_value !== '' && !preg_match('/^[a-zA-Z0-9_]+$/', $field_value)) {
      $errors['field_parameter_name'][$lang][0][] = array(
        'error' => 'field_parameter_name_invalid',
        'message' => t('The parameter name can only contain lowercase- and uppercase letters and numbers.'),
      );
    }
  }
}

/**
 * Implements template_preprocess_field().
 *
 * Add an extra class for severity field based on the selected item.
 */
function walkhub_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_severity_of_the_change' && isset($variables['element']['#items'][0]['value'])) {
    $variables['classes_array'][] = 'wt-severity-' . $variables['element']['#items'][0]['value'];
  }
}

/**
 * Implements hook_services_resources().
 */
function walkhub_services_resources() {
  $walkhub_resource = array();

  $inc = array(
    'type' => 'inc',
    'module' => 'walkhub',
  );
  $walkthroughinc = $inc + array(
    'name' => 'services/walkthrough',
  );
  $stepinc = $inc + array(
    'name' => 'services/step',
  );
  $commentinc = $inc + array(
    'name' => 'services/comment',
  );
  $listinc = $inc + array(
    'name' => 'services/list',
  );
  $listinginc = $inc + array(
    'name' => 'services/listing',
  );

  $walkhub_resource['walkhub-walkthrough'] = array(
    'retrieve' => array(
      'file' => $walkthroughinc,
      'callback' => '_walkthrough_resource_retrieve',
      'args' => array(
        array(
          'name' => 'walkthroughid',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'string',
        ),
      ),
      'access callback' => '_walkthrough_resource_access',
      'access callback file' => $walkthroughinc,
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
    ),
  );

  $walkhub_resource['walkhub-step'] = array(
    'operations' => array(
      'retrieve' => array(
        'file' => $stepinc,
        'callback' => '_step_resource_retrieve',
        'args' => array(
          array(
            'name' => 'stepid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
          ),
        ),
        'access callback' => '_step_resource_access',
        'access callback file' => $stepinc,
        'access arguments' => array('view'),
        'access arguments append' => TRUE,
      ),
      'update' => array(
        'file' => $stepinc,
        'callback' => '_step_resource_update',
        'args' => array(
          array(
            'name' => 'stepid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
          ),
          array(
            'name' => 'step',
            'optional' => FALSE,
            'source' => 'data',
            'type' => 'array',
          )
        ),
        'access callback' => '_step_resource_access',
        'access callback file' => $stepinc,
        'access arguments' => array('update'),
        'access arguments append' => TRUE,
      ),
    ),
  );

  $walkhub_resource['walkhub-comment'] = array();

  $walkhub_resource['walkhub-list'] = array(
    'retrieve' => array(
      'file' => $listinc,
      'callback' => '_list_resource_retrieve',
      'args' => array(
        array(
          'name' => 'listname',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'string',
        ),
      ),
      'access callback' => '_list_resource_access',
      'access callback file' => $listinc,
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
    ),
    'index' => array(
      'file' => $listinc,
      'callback' => '_list_resource_index',
      'access callback' => '_list_resource_access',
      'access callback file' => $listinc,
      'access arguments' => array('index'),
      'access arguments append' => TRUE,
      'args' => array(
        'name' => array(
          'name' => 'name',
          'type' => 'string',
          'description' => 'The name of the view',
          'source' => array('param' => 'name'),
          'optional' => TRUE,
          'default value' => '',
        ),
        'description' => array(
          'name' => 'description',
          'type' => 'string',
          'description' => 'The description of the view',
          'source' => array('param' => 'description'),
          'optional' => TRUE,
          'default value' => '',
        ),
        'tag' => array(
          'name' => 'tag',
          'type' => 'string',
          'description' => 'The tag of the view',
          'source' => array('param' => 'tag'),
          'optional' => TRUE,
          'default value' => '',
        ),
        'base_table' => array(
          'name' => 'base_table',
          'type' => 'string',
          'description' => 'The base table of the view',
          'source' => array('param' => 'base_table'),
          'optional' => TRUE,
          'default value' => '',
        ),
        'human_name' => array(
          'name' => 'human_name',
          'type' => 'string',
          'description' => 'The human name of the view',
          'source' => array('param' => 'human_name'),
          'optional' => TRUE,
          'default value' => '',
        ),
      ),
    ),
  );

  $walkhub_resource['walkhub-listing'] = array(
    'index' => array(
      'file' => $listinginc,
      'callback' => '_listing_resource_index',
      'access callback' => '_list_resource_access',
      'access callback file' => $listinginc,
      'access arguments' => array('index'),
      'access arguments append' => TRUE,
      'args' => array(),
    ),
  );

  $walkhub_resource['walkhub-step-suggestion'] = array(
    'index' => array(
      'file' => $listinc,
      'callback' => '_step_suggestion_retrieve',
      'access callback' => '_step_suggestion_resource_access',
      'access callback file' => $listinc,
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
      'args' => array(
        array(
          'name' => 'domain',
          'optional' => TRUE,
          'source' => array(
            'param' => 'domain',
          ),
          'type' => 'string',
          'default value' => '',
        ),
        array(
          'name' => 'command',
          'optional' => FALSE,
          'source' => array(
            'param' => 'command',
          ),
          'type' => 'string',
          'default value' => '',
        ),
        array(
          'name' => 'arg1',
          'optional' => TRUE,
          'source' => array(
            'param' => 'arg1',
          ),
          'type' => 'string',
          'default value' => '',
        ),
        array(
          'name' => 'arg2',
          'optional' => TRUE,
          'source' => array(
            'param' => 'arg2',
          ),
          'type' => 'string',
          'default value' => '',
        ),
        array(
          'name' => 'uid',
          'optional' => TRUE,
          'source' => array(
            'param' => 'uid',
          ),
          'type' => 'string',
          'default value' => '',
        ),
      ),
    ),
  );

  $walkhub_resource['walkthrough-prerequisites'] = array(
    'index' => array(
      'file' => $walkthroughinc,
      'callback' => '_walkthrough_prerequisites_retrieve',
      'access callback' => '_walkthrough_resource_access',
      'access callback file' => $walkthroughinc,
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
      'args' => array(
        array(
          'name' => 'uuid',
          'optional' => FALSE,
          'source' => array(
            'param' => 'uuid',
          ),
          'type' => 'string',
        ),
      ),
    ),
  );

  $walkhub_resource['walkthrough-phpunit'] = array(
    'retrieve' => array(
      'file' => $walkthroughinc,
      'callback' => '_walkthrough_phpunit_retrieve',
      'access callback' => '_walkthrough_resource_php_unit_export_access',
      'access callback file' => $walkthroughinc,
      'access arguments append' => TRUE,
      'args' => array(
        array(
          'name' => 'uuid',
          'optional' => FALSE,
          'source' => array(
            'path' => 0,
          ),
          'type' => 'string',
        ),
        array(
          'name' => 'class_to_extend',
          'optional' => TRUE,
          'source' => array(
            'path' => 1,
          ),
          'type' => 'string',
          'default value' => 'PHPUnit_Extensions_Selenium2TestCase',
        ),
      ),
    ),
  );

  $walkhub_resource['walkthrough-screening-flag'] = array(
    'operations' => array(
      'update' => array(
        'file' => $walkthroughinc,
        'callback' => '_walkthrough_update_screening_flag',
        'args' => array(
          array(
            'name' => 'uuid',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'string',
          ),
          array(
            'name' => 'flag',
            'optional' => FALSE,
            'source' => 'data',
            'type' => 'boolean',
          )
        ),
        'access callback' => '_walkthrough_or_walkthrough_set_resource_access',
        'access arguments' => array('update'),
        'access callback file' => $walkthroughinc,
        'access arguments append' => TRUE,
      ),
    ),
  );

  return $walkhub_resource;
}

/**
 * Implements hook_node_presave().
 *
 * @param $node
 */
function walkhub_node_presave($node) {

  if ($node->type == 'walkthrough' && !empty($node->field_raw_input[LANGUAGE_NONE][0]['value']) && empty($node->nid) && !isset($node->clone_from_original_nid)) {
    $source = field_get_items('node', $node, 'field_raw_input', LANGUAGE_NONE);
    if (($result = _walkhub_break_up_to_steps_json($source[0]['value']))) {
      list($steps, $base) = $result;
    } else {
      list($steps, $base) = _walkhub_break_up_to_steps_html($source[0]['value']);
    }

    if ($base) {
      _walkhub_add_default_parameters($base, $node);
    }

    $steps = _walkhub_filter_steps($steps);

    if (!empty($steps)) {
      // Create new nodes based on the selenium source.
      $walkthrough_steps = array();
      foreach ($steps as $key => $step) {
        $steps[$key]['fci'] = _walkhub_create_step($step, $key, $node);
        $walkthrough_steps[$key]['value'] = $steps[$key]['fci']->identifier();
        $walkthrough_steps[$key]['revision_id'] = $steps[$key]['fci']->revision_id;
      }
      $node->field_fc_steps[LANGUAGE_NONE] = $walkthrough_steps;
    }
  }
}

/**
 * Filters walkhub steps, so we can ignore/disable steps we don't want to store.
 *
 * @param array $steps
 * @return array
 */
function _walkhub_filter_steps(array $steps) {
  $ignored_steps = array('waitForPageToLoad');

  $steps = array_filter($steps, function($step) use ($ignored_steps) {
    return (!in_array($step['action'], $ignored_steps));
  });

  return $steps;
}

/**
 * Check that the currently logged in user has the right permission to export
 * walkthroughs.
 *
 * @param $node
 * @return bool
 */
function walkhub_export_access($node) {
  global $user;

  if ($user->uid == 1 || user_access('bypass node access')) {
    return TRUE;
  }

  if (user_access('export any walkthrough')) {
    return TRUE;
  }

  if (user_access('export own walkthrough') && $node->uid == $user->uid) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Adds the 'domain' as a default parameter to the node object.
 *
 * @param string $base
 *   THe base url from the selenium test.
 * @param stdClass $node
 *   THe newly created node object.
 */
function _walkhub_add_default_parameters($base, $node) {
  $host = parse_url($base, PHP_URL_HOST);
  $item = new FieldCollectionItemEntity();
  $item->is_new = TRUE;
  $item->field_name = 'field_parameters';
  $item->setHostEntity('node', $node, $node->language, FALSE);
  $item->field_parameter_name[$node->language][0]['value'] = 'domain';
  $item->field_parameter_default_value[$node->language][0]['value'] = $host;
  $item->save(TRUE);
  $node->field_parameters[$node->language][] = array(
    'value' => $item->identifier(),
    'revision_id' => $item->revision_id,
  );

  if (isset($node->__password_parameter) && $node->__password_parameter) {
    $pwitem = new FieldCollectionItemEntity();
    $pwitem->is_new = TRUE;
    $pwitem->field_name = 'field_parameters';
    $pwitem->setHostEntity('node', $node, $node->language, FALSE);
    $pwitem->field_parameter_name[$node->language][0]['value'] = 'password';
    $pwitem->field_parameter_default_value[$node->language][0]['value'] = '';
    $pwitem->save(TRUE);
    $node->field_parameters[$node->language][] = array(
      'value' => $pwitem->identifier(),
      'revision_id' => $pwitem->revision_id,
    );
  }
}

/**
 * Implements hook_entity_presave().
 */
function walkhub_entity_presave($entity, $type) {
  if ($type === 'field_collection_item' && $entity->field_name === 'field_parameters') {
    $parameter_name = $entity->field_parameter_name[LANGUAGE_NONE][0]['value'];
    if ($parameter_name === 'domain') {
      $url = $entity->field_parameter_default_value[LANGUAGE_NONE][0]['value'];
      $domain = _walkhub_get_domain_from_walkthrough_url_parameter($url);
      if ($domain !== $url) {
        $entity->field_parameter_default_value[LANGUAGE_NONE][0]['value'] = $domain;
      }
    }
  }
}

/**
 * Returns the domain from the $url
 *
 * @param string $url
 *   The provided content for the $url parameter value
 *
 * @return string
 *   [domain]/[path]
 */
function _walkhub_get_domain_from_walkthrough_url_parameter($url) {
  $parsed_url = parse_url($url);
  if (array_key_exists('host', $parsed_url)) {
    $result =  $parsed_url['host'];
    if (!empty($parsed_url['path']) && $parsed_url['path'] !== '/') {
      $result .= $parsed_url['path'];
    }
  } else {
    $result = preg_replace('#^http[s]?://#', '', $url);
  }
  $result = rtrim($result, '/');

  return $result;
}

/**
 * Breaks up the json formatted $source input into steps.
 *
 * @param string $source
 *   JSON-encoded list of steps.
 * @return array|null
 *   Array of steps or NULL on failure.
 */
function _walkhub_break_up_to_steps_json($source) {
  $decoded = json_decode($source, TRUE);
  if (json_last_error() !== JSON_ERROR_NONE) {
    return NULL;
  }

  $base = NULL;
  if (count($decoded) && $decoded[0]['cmd'] === 'open') {
    $base = $decoded[0]['arg0'];
    $decoded[0]['arg0'] = http_build_url($decoded[0]['arg0'], array(
      'host' => '[domain]',
    ));
  }

  $highlightdata = _walkhub_get_supported_selenium_commands();
  return array(array_map(function ($item) use (&$highlightdata) {
    return array(
      'action' => $item['cmd'],
      'xpath' => $item['arg0'],
      'description' => $item['arg1'],
      'highlight' => isset($highlightdata[$item['cmd']]) ?
        ($highlightdata[$item['cmd']] ? $item['arg1'] : $item['arg0']) : '',
    );
  }, $decoded), $base);
}

function _walkhub_get_origin($url) {
  $parsed = parse_url($url);
  unset($parsed['path']);
  unset($parsed['query']);
  unset($parsed['fragment']);

  return http_build_url($parsed);
}

/**
 * Break up to steps $source selenium input.
 *
 * @param $source
 * @return array
 */
function _walkhub_break_up_to_steps_html($source) {
  $highlightdata = _walkhub_get_supported_selenium_commands();

  // Change <br /> to newlines.
  $source = preg_replace('#<br\s*/?>#i', "\n", $source);

  $steps = array();
  $first = TRUE;
  $doc = new DOMDocument();
  // Load the selenium test case.
  $doc->loadHTML($source);
  $basexpath = new DOMXPath($doc);
  $baseList = $basexpath->query('//link[@rel="selenium.base"]');
  $base = $baseList->length ? $baseList->item(0)->getAttribute('href') : NULL;
  $xpath = new DOMXpath($doc);
  // Break up to steps.
  $elements = $xpath->query('//tbody/tr');
  if ($elements->length) {
    // Loop through the steps.
    foreach ($elements as $step => $element) {
      // Get the step attributes.
      $attributes = $element->getElementsByTagName('td');
      foreach ($attributes as $key => $attribute) {
        switch ($key) {
          case 0:
            $steps[$step]['action'] = $attribute->nodeValue;
            break;
          case 1:
            $steps[$step]['xpath'] = $attribute->nodeValue;
            break;
          case 2:
            $steps[$step]['description'] = $attribute->nodeValue;
            break;
        }
      }
      $act = endsWith($steps[$step]['action'], 'AndWait') ?
        substr($steps[$step]['action'], 0, -7) : $steps[$step]['action'];
      $steps[$step]['highlight'] = isset($highlightdata[$act]) ?
        ($highlightdata[$act] ? $steps[$step]['description'] : $steps[$step]['xpath']) : '';
      // Makes all URLs absolute ones.
      if ($steps[$step]['action'] === 'open') {
        $components = parse_url($steps[$step]['xpath']);
        if (empty($components['host'])) {
          $steps[$step]['xpath'] = _walkhub_assemble_url($base, $steps[$step]['xpath'], $first);
          if ($first) {
            $first = FALSE;
          }
        }
      }
    }
  }
  // TODO I think this function should be an iterator object.
  return array($steps, $base);
}

/**
 * Returns with the supported selenium commands list.
 *
 * @return array
 */
function _walkhub_get_supported_selenium_commands() {
  return array(
    'addSelection' => 0,
    'assignId' => 0,
    'check' => 0,
    'click' => 0,
    'clickAt' => 0,
    'contextMenu' => 0,
    'contextMenuAt' => 0,
    'doubleClick' => 0,
    'doubleClickAt' => 0,
    'dragAndDrop' => 0,
    'dragAndDropToObject' => 0,
    'dragdrop' => 0,
    'fireEvent' => 0,
    'focus' => 0,
    'highlight' => 0,
    'keyDown' => 0,
    'keyPress' => 0,
    'keyUp' => 0,
    'mouseDown' => 0,
    'mouseDownAt' => 0,
    'mouseDownRight' => 0,
    'mouseDownRightAt' => 0,
    'mouseMove' => 0,
    'mouseMoveAt' => 0,
    'mouseOut' => 0,
    'mouseOutAt' => 0,
    'mouseOver' => 0,
    'mouseUp' => 0,
    'mouseUpAt' => 0,
    'mouseUpRight' => 0,
    'mouseUpRightAt' => 0,
    'removeAllSelections' => 0,
    'removeSelection' => 0,
    'sendKeys' => 0,
    'select' => 0,
    'selectFrame' => 0,
    'setCursorPosition' => 0,
    'submit' => 0,
    'type' => 0,
    'typeKeys' => 0,
    'uncheck' => 0,
  );
}

function endsWith($haystack, $needle) {
  return substr($haystack, -strlen($needle)) == $needle;
}

function _walkhub_assemble_url($base, $url, $parameter = FALSE) {
  if ($url[0] === '/') {
    $base_parts = parse_url($base);
    $base = $base_parts['scheme'] . '://';
    if (!empty($base_parts['user']) || !empty($base_parts['pass'])) {
      if (!empty($base_parts['user'])) {
        $base .= $base_parts['user'];
      }
      if (!empty($base_parts['pass'])) {
        $base .= ':' . $base_parts['pass'];
      }
      $base .= '@';
    }
    $base .= $parameter ? '[domain]' : $base_parts['host'];
    if (!empty($base_parts['port'])) {
      $base .= ':' . $base_parts['port'];
    }
  }

  return trim($base, '/') . '/' . trim($url, '/');
}

/**
 *
 *
 * @param $source
 * @return string
 */
function _walkhub_parse_url($source) {
  $doc = new DOMDocument();
  // Load the selenium test case.
  $doc->loadHTML($source);
  $link = $doc->getElementsByTagName('link');
  $url = $link->item(0)->getAttribute('href');
  return $url;
}

/**
 * Create a step node.
 *
 * @param array $step
 * @param int $key
 * @param stdClass $walkthrough_node
 * @return FieldCollectionItemEntity
 */
function _walkhub_create_step(array $step, $key, $walkthrough_node) {
  $lang = $walkthrough_node->language;
  $fci = entity_create('field_collection_item', array('field_name' => 'field_fc_steps'));
  $fci->setHostEntity('node', $walkthrough_node, $lang, FALSE);
  $fci->field_fc_step_name[$lang][0]['value'] = " ";
  $fci->field_fc_step_description[$lang][0]['value'] = walkhub_get_default_step_description($step['action']);
  $fci->field_fc_step_command_1[$lang][0]['value'] = $step['action'];
  $fci->field_fc_step_command_2[$lang][0]['value'] = $step['xpath'];
  $fci->field_fc_step_command_3[$lang][0]['value'] = $step['description'];
  $fci->field_fc_step_highlight[$lang][0]['value'] = $step['highlight'];

  drupal_alter('walkhub_import_step', $fci);

  $fci->save(TRUE);

  return $fci;
}

/**
 * Extracts parameter data from a walkthrough node.
 *
 * @param stdClass $walkthrough
 *   Walkthrough node.
 *
 * @return array
 *   Array in a format of $parameter => $default_value.
 */
function _walkhub_get_parameters($walkthrough) {
  $result = array();

  if ($walkthrough->field_parameters) {
    $parameters = field_collection_item_load_multiple(array_map(function ($item) {
      return $item['value'];
    }, $walkthrough->field_parameters[$walkthrough->language]));
    foreach ($parameters as $parameterdata) {
      if (!($langcode = $parameterdata->langcode())) {
        $langcode = LANGUAGE_NONE;
      }
      $parameter = isset($parameterdata->field_parameter_name[$langcode][0]['safe_value']) ?
        $parameterdata->field_parameter_name[$langcode][0]['safe_value'] : NULL;
      $value = isset($parameterdata->field_parameter_default_value[$langcode][0]['safe_value']) ?
        $parameterdata->field_parameter_default_value[$langcode][0]['safe_value'] : NULL;
      if ($parameter !== NULL) {
        $result[$parameter] = $value;
      }
    }
  }

  return $result;
}

/**
 * Implements hook_walkhub_client_paths().
 */
function walkhub_walkhub_client_paths() {
  return array(
    'walkhub',
  );
}

/**
 * Return the default pattern for a command.
 *
 * @param $command
 *  Name of the selenium command.
 * @return mixed
 *  Default pattern for the given command.
 */
function walkhub_get_default_step_description($command) {
  return db_select('walhub_patterns')
    ->fields('walhub_patterns', array('pattern'))
    ->condition('command', $command)
    ->execute()->fetchField();
}

/**
 * Implements hook_field_collection_item_view().
 */
function walkhub_field_collection_item_view($field_collection_item, $view_mode, $langcode) {
  if ($field_collection_item->field_name === WALKTHROUGH_FIELD_STEPS) {
    $step = walkhub_get_position_from_step($field_collection_item->hostEntityId(), $field_collection_item->item_id);
    // Display the position of the step in the begining of the field view.
    $field_collection_item->content['position'] = array(
      '#prefix' => '<span class="wt-step-position">',
      '#markup' => $step,
      '#suffix' => '</span>',
      '#weight' => -30,
    );
  }
}

/**
 * Return the position of the given step in the given walkthrough.
 *
 * @param $walkthrough_id
 *   Id of the walkthrough node.
 * @param $step_id
 *   Id of the step field collection item.
 * @return int
 *   The position of the appropriate step in a walkthrough.
 */
function walkhub_get_position_from_step($walkthrough_id, $step_id) {
  $positions = &drupal_static(__FUNCTION__, array());

  if (!empty($positions[$walkthrough_id][$step_id])) {
    return $positions[$walkthrough_id][$step_id];
  }

  $walkthrough =node_load($walkthrough_id);
  $steps = field_get_items('node', $walkthrough, WALKTHROUGH_FIELD_STEPS);

  // Get the position of the actual step in the walkthrough.
  foreach ($steps as $key => $value) {
    if ($value['value'] === $step_id) {
      // We want to start the numbering from 1 instead of 0.
      $position = $key+1;
      $positions[$walkthrough_id][$step_id] = $position;
    }
  }

  return $position;
}

/**
 * Implements hook_preprocess_HOOK();
 */
function walkhub_preprocess_html(&$vars) {
  // Add full window class, if the appropriate parameter has been added.
  $vars['classes_array'][] = !empty($_GET['wt_full_window']) ? 'walkthrough-full-window' : '';
  $vars['classes_array'][] = !empty($_GET['wt_play_prerequisites']) ? 'walkthrough-play-prerequisites' : '';
}

/**
 * Helper function determine if the walkthrough node page should only display the start walkthrough button.
 *
 * @return bool
 */
function walkhub_is_button_page() {
  return !empty($_GET['buttononly']) && ($node = menu_get_object('node')) && $node->type == 'walkthrough';
}

/**
 * Implements hook_page_alter().
 */
function walkhub_page_alter(&$page) {
  if (walkhub_is_button_page() && module_exists('admin_menu')) {
    admin_menu_suppress();
  }
}

/**
 * Implements hook_preprocess_page().
 */
function walkhub_preprocess_page(&$variables) {
  if (walkhub_is_button_page()) {
    $variables['theme_hook_suggestions'][] = 'page__node__walkhub__button';
  }
}

/**
 * Implements hook_theme().
 */
function walkhub_theme() {
  $module_path = drupal_get_path('module', 'walkhub');

  return array(
    'page__node__walkhub__button' => array(
      'render element' => 'page',
      'template' => 'page__node__walkhub__button',
      'base hook' => 'page',
      'path' => $module_path,
    ),
    'walkthrough__record__block' => array(
      'variables' => array('form' => NULL),
      'template' => 'walkthrough__record__block',
      'path' => $module_path,
    ),
  );
}

/**
 * Returns a hash based on a node.
 *
 * @param stdClass $node
 * @return string
 *   sha1 hash
 */
function walkhub_get_id_hash($node) {
  return sha1($node->uuid . $_SERVER['SERVER_NAME']);
}

/**
 * Returns the origin (protocol + hostname + port) of this server.
 *
 * @return string
 */
function walkhub_get_origin() {
  global $is_https;
  return 'http' . ($is_https ? 's' : '') . "://{$_SERVER['SERVER_NAME']}" . (in_array($_SERVER['SERVER_PORT'], array(80, 443)) ? '' : ":{$_SERVER['SERVER_PORT']}");
}


/**
 * Form for the walkhub recorder.
 */
function walkhub_record_form($form, &$form_state, $floating_record_button = FALSE) {
  $module_path = drupal_get_path('module', 'walkhub');

  $form['#attributes'] = array('class' => array('walkhub-record-form'));

  $form['#action'] = url('walkthrough/record/');
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#required' => TRUE,
  );

  $severity_field = field_info_field('field_severity_of_the_change');
  $severity_info_instance = field_info_instance('node', 'field_severity_of_the_change', 'walkthrough');
  $form['severity'] = array(
    '#type' => 'select',
    '#title' => $severity_info_instance['label'],
    '#required' => TRUE,
    '#options' => $severity_field['settings']['allowed_values'],
  );

  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('Starting URL'),
    '#attributes' => array(
      'class' => array('edit-url'),
    ),
  );

  $form['use_proxy'] = array(
    '#type' => 'checkbox',
    '#title' => t('Record the walkthrough over the WalkHub proxy (in case you don\'t have the browser or site plugin available)'),
    '#default_value' => 1,
    '#attributes' => array(
      'class' => array('edit-use-proxy'),
    ),
  );

  $form['record'] = array(
    '#type' => 'button',
    '#value' => t('Record'),
    '#attributes' => array(
      'data-proxy-url' => variable_get('walkhub_proxy_url'),
      'class' => array('edit-record'),
    ),
  );

  $form['steps'] = array(
    '#type' => 'textarea',
    '#title' => t('Steps'),
  );

  $form['password_parameter'] = array(
    '#type' => 'checkbox',
    '#title' => t('Generate password parameter'),
  );

  $form['stepcontainer'] = array(
    '#markup' => '<h3>Recorded steps</h3><ul id="steps"></ul>',
  );

  $form['save'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  $form['#attached'] = array(
    'js' => array(
      $module_path . '/walkhub.js',
    ),
    'css' => array(
      $module_path . '/walkhub.css',
    ),
  );

  if ($floating_record_button) {
    $form["#attached"]['js'][] = $module_path . '/walkthrough_record_block.js';
    $form["#attached"]['css'][] = $module_path . '/walkthrough_record_block.css';
  }

  return $form;
}
