<?php
/**
 * @file
 * Code for the Walkthrough sets feature.
 */

include_once 'walkthrough_sets.features.inc';

/**
 * Implements hook_services_resources().
 */
function walkthrough_sets_services_resources() {
  $walkthrough_set_resource = array();

  $inc = array(
    'type' => 'inc',
    'module' => 'walkthrough_sets',
  );
  $setinc = $inc + array(
    'name' => 'services/set',
  );

  $walkthrough_set_resource['walkthrough-set'] = array(
    'retrieve' => array(
      'file' => $setinc,
      'callback' => '_walkthrough_set_resource_retrieve',
      'args' => array(
        array(
          'name' => 'walkthroughsetid',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'string',
        ),
      ),
      'access callback' => '_walkthrough_set_resource_access',
      'access callback file' => $setinc,
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
    ),
  );

  return $walkthrough_set_resource;
}

/**
 * Implements hook_node_view_alter().
 */
function walkthrough_sets_node_view_alter(&$build) {
  if ($build['#node']->type === 'walkthrough_set') {
    $node = $build['#node'];
    $parameters = _walkhub_get_parameters($node);
    $refs = _walkthrough_sets_get_references($node);
    $links = array();
    foreach ($refs as $ref) {
      $links[] = array(
        'title' => $ref['walkthrough']->title,
        'href' => "node/{$ref['walkthrough']->nid}",
        'query' => $ref['parameters'] + $parameters + array('autostart' => 1),
      );
    }
    $build = array(
      'set_links' => array(
        '#theme' => 'links',
        '#links' => $links,
      ),
    ) + $build;
  }
}

/**
 * Extracts the references from a walkthrough set node.
 *
 * @param stdClass $set
 *   Node to extract the data from.
 *
 * @return array
 *   List of a data array with two keys. The first key, 'walkthrough' is a
 *   reference to the walkthrough node, the second key, 'parameters' are the
 *   list of the custom parameters for this reference.
 *
 * @see _walkhub_get_parameters()
 */
function _walkthrough_sets_get_references($set) {
  $refs = array();

  if ($set->field_walkthroughs) {
    module_load_include('inc', 'walkhub');
    $fc_refs = field_collection_item_load_multiple(array_map(function ($item) {
      return $item['value'];
    }, $set->field_walkthroughs[$set->language]));
    foreach ($fc_refs as $fc_ref) {
      $fc_ref->language = $fc_ref->langcode() ?: LANGUAGE_NONE;
      $refs[] = array(
        'walkthrough' => node_load(walkhub_field_get_value($fc_ref, 'field_walkthrough', FALSE, $fc_ref->language, 'target_id')),
        'parameters' => _walkhub_get_parameters($fc_ref),
      );
    }
  }

  return $refs;
}

