<?php
/**
 * @file
 * Code for the Walkthrough sets feature.
 */

include_once 'walkthrough_sets.features.inc';

/**
 * Implements hook_services_resources().
 */
function walkthrough_sets_services_resources() {
  $walkthrough_set_resource = array();

  $inc = array(
    'type' => 'inc',
    'module' => 'walkhub_sets',
  );
  $setinc = $inc + array(
    'name' => 'services/set',
  );

  $walkthrough_set_resource['walkthrough-set'] = array(
    'retrieve' => array(
      'file' => $setinc,
      'callback' => '_walkthrough_set_resource_retrieve',
      'args' => array(
        array(
          'name' => 'walkthroughsetid',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'string',
        ),
      ),
      'access callback' => '_walkthrough_set_resource_access',
      'access callback file' => $setinc,
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
    ),
  );

  return $walkthrough_set_resource;
}
