<?php
/**
 * @file
 * Code for the Walkthrough sets feature.
 */

include_once 'walkthrough_sets.features.inc';

/**
 * Implements hook_services_resources().
 */
function walkthrough_sets_services_resources() {
  $walkthrough_set_resource = array();

  $inc = array(
    'type' => 'inc',
    'module' => 'walkthrough_sets',
  );
  $setinc = $inc + array(
    'name' => 'services/set',
  );

  $walkthrough_set_resource['walkthrough-set'] = array(
    'retrieve' => array(
      'file' => $setinc,
      'callback' => '_walkthrough_set_resource_retrieve',
      'args' => array(
        array(
          'name' => 'walkthroughsetid',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'string',
        ),
      ),
      'access callback' => '_walkthrough_set_resource_access',
      'access callback file' => $setinc,
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
    ),
  );

  return $walkthrough_set_resource;
}

/**
 * Implements hook_node_view_alter().
 */
function walkthrough_sets_node_view_alter(&$build) {
  if ($build['#node']->type === 'walkthrough_set') {
    $node = $build['#node'];
    $parameters = _walkhub_get_parameters($node);
    $refs = _walkthrough_sets_get_references($node);
    $links = array();
    foreach ($refs as $ref) {
      $links[] = array(
        'title' => $ref['walkthrough']->title,
        'href' => "node/{$ref['walkthrough']->nid}",
        'query' => $ref['parameters'] + $parameters + array('autostart' => 1),
      );
    }
    $build = array(
      'set_links' => array(
        '#theme' => 'links',
        '#links' => $links,
      ),
    ) + $build;
  }
}

/**
 * Extracts the references from a walkthrough set node.
 *
 * @param stdClass $set
 *   Node to extract the data from.
 *
 * @return array
 *   List of a data array with two keys. The first key, 'walkthrough' is a
 *   reference to the walkthrough node, the second key, 'parameters' are the
 *   list of the custom parameters for this reference.
 *
 * @see _walkhub_get_parameters()
 */
function _walkthrough_sets_get_references($set) {
  $refs = array();

  if ($set->field_walkthroughs) {
    module_load_include('inc', 'walkhub');
    $fc_refs = field_collection_item_load_multiple(array_map(function ($item) {
      return $item['value'];
    }, $set->field_walkthroughs[$set->language]));
    foreach ($fc_refs as $fc_ref) {
      $fc_ref->language = $fc_ref->langcode() ?: LANGUAGE_NONE;
      $refs[] = array(
        'walkthrough' => node_load(walkhub_field_get_value($fc_ref, 'field_walkthrough', FALSE, $fc_ref->language, 'target_id')),
        'parameters' => _walkhub_get_parameters($fc_ref),
      );
    }
  }

  return $refs;
}

/**
 * Implements hook_extra_fields().
 */
function walkthrough_sets_field_extra_fields() {
  $extra_fields['node']['walkthrough'] = array(
    'display' => array(
      'walkthrough_sets_step_list' => array(
        'label' => t('Rendered step list'),
        'description' => t(''),
        'weight' => 0,
      ),
    ),
  );

  return $extra_fields;
}

/**
 * Implements hook_node_view().
 */
function walkthrough_sets_node_view($node, $view_mode) {
  if ($node->type == 'walkthrough') {
    $steps = array_map(
      function($step) {
        return node_load($step['target_id']);
      },
      $node->field_steps[LANGUAGE_NONE]
    );

    $node->content['walkthrough_sets_step_list'] = array(
      '#theme' => 'walkthrough_sets_list_steps',
      '#walkthrough_steps' => $steps,
      '#weight' => 10,
    );
  }
}

/**
 * Implements hook_theme().
 */
function walkthrough_sets_theme($existing, $type, $theme, $path) {
  return array(
    'walkthrough_sets_list_steps' => array(
      'variables' => array(
        'walkthrough_steps' => array(),
      ),
    ),
    'walkthrough_step' => array(
      'variables' => array(
        'node' => new stdClass(),
      ),
      'path' => drupal_get_path('module', 'walkthrough_sets') . '/templates/',
      'template' => 'walkthrough_step',
    ),
  );
}

/**
 * Theme callback for rendering the steps list.
 *
 * @param array $steps
 *   Array of node objects.
 */
function theme_walkthrough_sets_list_steps(array $steps) {
  $rendered_steps = array_map(
    function($node) {
      node_build_content($node);
      return theme('walkthrough_step', array('node' => $node));
    },
    $steps['walkthrough_steps']
  );

  return theme('item_list', array('items' => $rendered_steps));
}

